# Generated by Django 5.2.6 on 2025-10-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the external event (e.g., webhook event ID, timer timestamp)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the execution was created"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the execution actually started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the execution completed (success or failed)",
                        null=True,
                    ),
                ),
                (
                    "trigger_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data from the trigger/action that initiated this execution",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result data from the reaction execution",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if execution failed",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this execution has been retried",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automations.area",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["area", "status"], name="automations_area_id_531114_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="automations_created_257c0b_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="automations_status_50babf_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("area", "external_event_id"),
                        name="unique_area_external_event",
                    )
                ],
            },
        ),
    ]
