# Generated by Django 5.2.6 on 2025-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('paused', 'Paused')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
