# Generated by Django 5.2.6 on 2025-10-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful check', null=True)),
                ('last_event_id', models.CharField(blank=True, default='', help_text='ID of the last processed event (issue ID, commit SHA, etc.)', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional state data (ETags, cursor tokens, etc.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.OneToOneField(help_text='The Area this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='action_state', to='automations.area')),
            ],
            options={
                'verbose_name': 'Action State',
                'verbose_name_plural': 'Action States',
                'indexes': [models.Index(fields=['last_checked_at'], name='automations_last_ch_e608e3_idx')],
            },
        ),
    ]
