# Generated by Django 5.2.6 on 2025-10-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_actionstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='config_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema defining required configuration fields for this action'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='config_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema defining required configuration fields for this reaction'),
        ),
    ]
