# Generated by Django 5.2.6 on 2025-10-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0005_action_config_schema_reaction_config_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External service's subscription ID (e.g., Twitch EventSub ID)",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of event (e.g., 'stream.online', 'issues', 'message')",
                        max_length=100,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Webhook configuration (e.g., repository, channel, broadcaster_id)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Verification"),
                            ("failed", "Failed"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_event_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last received webhook event",
                        null=True,
                    ),
                ),
                (
                    "event_count",
                    models.IntegerField(
                        default=0, help_text="Total number of events received"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_subscriptions",
                        to="automations.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Subscription",
                "verbose_name_plural": "Webhook Subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "service", "status"],
                        name="automations_user_id_744fad_idx",
                    ),
                    models.Index(
                        fields=["external_subscription_id"],
                        name="automations_externa_f427b0_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="automations_status_0404a6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "service", "event_type", "config"),
                        name="unique_user_webhook_subscription",
                    )
                ],
            },
        ),
    ]
