# Generated by Django 5.2.6 on 2025-10-28 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0006_add_webhook_subscription_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubAppInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation_id",
                    models.BigIntegerField(
                        help_text="GitHub App installation ID", unique=True
                    ),
                ),
                (
                    "account_login",
                    models.CharField(
                        help_text="GitHub username or organization name", max_length=255
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("User", "User"), ("Organization", "Organization")],
                        default="User",
                        max_length=20,
                    ),
                ),
                (
                    "repositories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of repo full names (e.g., ['owner/repo1', 'owner/repo2'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False if user uninstalled the app"
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="AREA user who installed the app",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_app_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "github_app_installations",
                "indexes": [
                    models.Index(
                        fields=["user", "installation_id"],
                        name="github_app__user_id_3aaa27_idx",
                    ),
                    models.Index(
                        fields=["installation_id"],
                        name="github_app__install_f5a187_idx",
                    ),
                    models.Index(
                        fields=["account_login"], name="github_app__account_e625f2_idx"
                    ),
                ],
            },
        ),
    ]
