# Generated by Django 5.2.6 on 2025-10-30 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_githubappinstallation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchEventSubSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='Twitch EventSub subscription ID', max_length=255, unique=True)),
                ('subscription_type', models.CharField(choices=[('stream.online', 'Stream Online'), ('stream.offline', 'Stream Offline'), ('channel.update', 'Channel Update'), ('channel.follow', 'Channel Follow'), ('channel.subscribe', 'Channel Subscribe')], help_text='Type of Twitch event to subscribe to', max_length=50)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('webhook_callback_verification_pending', 'Webhook Callback Verification Pending'), ('webhook_callback_verification_failed', 'Webhook Callback Verification Failed'), ('notification_failures_exceeded', 'Notification Failures Exceeded'), ('authorization_revoked', 'Authorization Revoked'), ('moderator_removed', 'Moderator Removed'), ('user_removed', 'User Removed'), ('version_removed', 'Version Removed')], default='enabled', help_text='Current status of the subscription', max_length=50)),
                ('condition', models.JSONField(default=dict, help_text="EventSub condition parameters (e.g., {'broadcaster_user_id': '12345'})")),
                ('broadcaster_login', models.CharField(blank=True, help_text='Twitch username being monitored (cached)', max_length=255)),
                ('broadcaster_user_id', models.CharField(blank=True, help_text='Twitch user ID being monitored', max_length=100)),
                ('cost', models.IntegerField(default=0, help_text='EventSub subscription cost (for quota tracking)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='AREA user who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='twitch_eventsub_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'twitch_eventsub_subscriptions',
                'indexes': [models.Index(fields=['user', 'subscription_type'], name='twitch_even_user_id_40f16e_idx'), models.Index(fields=['subscription_id'], name='twitch_even_subscri_1a166a_idx'), models.Index(fields=['status'], name='twitch_even_status_c0a696_idx'), models.Index(fields=['broadcaster_user_id'], name='twitch_even_broadca_96990b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subscription_type', 'broadcaster_user_id'), name='unique_user_type_broadcaster')],
            },
        ),
    ]
