# Generated by Django 5.2.6 on 2025-10-31 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0008_twitcheventsubsubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TwitchEventSubSubscription",
        ),
    ]
