# Generated by Django 5.2.6 on 2025-10-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0010_remove_twitch_eventsub"),
    ]

    operations = [
        # Remove the old constraint that uses JSONField (config)
        migrations.RemoveConstraint(
            model_name="webhooksubscription",
            name="unique_user_webhook_subscription",
        ),
        # Add the correct constraint using external_subscription_id
        migrations.AddConstraint(
            model_name="webhooksubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "service", "event_type", "external_subscription_id"),
                name="unique_user_webhook_subscription",
            ),
        ),
    ]
