# Generated by Django 5.2.6 on 2025-11-02 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0011_fix_webhook_subscription_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWebhookWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('gmail', 'Gmail'), ('calendar', 'Google Calendar'), ('youtube', 'YouTube')], help_text='Google service being watched', max_length=20)),
                ('channel_id', models.CharField(db_index=True, help_text='Unique UUID identifying this watch (generated by us)', max_length=255, unique=True)),
                ('resource_id', models.CharField(help_text='Resource ID returned by Google after creating the watch', max_length=255)),
                ('resource_uri', models.CharField(blank=True, default='', help_text='Optional: Specific resource being watched (e.g., calendar ID)', max_length=500)),
                ('expiration', models.DateTimeField(help_text='When this watch expires (must renew before this time)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_event_at', models.DateTimeField(blank=True, help_text='Timestamp of the last received push notification', null=True)),
                ('event_count', models.IntegerField(default=0, help_text='Total number of push notifications received')),
                ('user', models.ForeignKey(help_text='User who owns this watch', on_delete=django.db.models.deletion.CASCADE, related_name='google_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Webhook Watch',
                'verbose_name_plural': 'Google Webhook Watches',
                'indexes': [models.Index(fields=['user', 'service'], name='automations_user_id_51fc8b_idx'), models.Index(fields=['expiration'], name='automations_expirat_105152_idx'), models.Index(fields=['channel_id'], name='automations_channel_8d45ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service', 'resource_uri'), name='unique_user_google_watch')],
            },
        ),
    ]
