# Generated by Django 5.2.6 on 2025-11-01 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0011_fix_webhook_subscription_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionWebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        help_text="Notion webhook ID from API",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "workspace_id",
                    models.CharField(help_text="Notion workspace ID", max_length=255),
                ),
                (
                    "page_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Notion page ID (if webhook is for specific page)",
                        max_length=255,
                    ),
                ),
                (
                    "database_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Notion database ID (if webhook is for specific database)",
                        max_length=255,
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        default=list,
                        help_text="List of event types (e.g., ['page.updated', 'database.updated'])",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Verification"),
                            ("failed", "Failed"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_event_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last received webhook event",
                        null=True,
                    ),
                ),
                (
                    "event_count",
                    models.IntegerField(
                        default=0, help_text="Total number of events received"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area that triggered this webhook creation (for automatic management)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_webhooks",
                        to="automations.area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="AREA user who owns this webhook",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_webhook_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notion Webhook Subscription",
                "verbose_name_plural": "Notion Webhook Subscriptions",
                "db_table": "notion_webhook_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notion_webh_user_id_fa09af_idx"
                    ),
                    models.Index(
                        fields=["webhook_id"], name="notion_webh_webhook_fe2f06_idx"
                    ),
                    models.Index(
                        fields=["workspace_id"], name="notion_webh_workspa_ac9de1_idx"
                    ),
                ],
            },
        ),
    ]
