# Generated by Django 5.2.6 on 2025-11-01 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0012_add_notion_webhook_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(db_index=True, help_text='Notion page or database UUID', max_length=255)),
                ('page_type', models.CharField(choices=[('page', 'Page'), ('database', 'Database')], default='page', help_text='Whether this is a page or database', max_length=20)),
                ('title', models.CharField(help_text='Page or database title', max_length=500)),
                ('workspace_id', models.CharField(help_text='Notion workspace ID', max_length=255)),
                ('icon', models.JSONField(blank=True, help_text='Notion page icon (emoji or URL)', null=True)),
                ('parent', models.JSONField(blank=True, help_text='Parent page/database info', null=True)),
                ('url', models.URLField(blank=True, help_text='Notion page URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_accessible', models.BooleanField(default=True, help_text='False if Notion API returns 404/403 (user revoked access)')),
                ('user', models.ForeignKey(help_text='AREA user who authorized this page', on_delete=django.db.models.deletion.CASCADE, related_name='notion_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notion Page',
                'verbose_name_plural': 'Notion Pages',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'page_type'], name='automations_user_id_49a887_idx'), models.Index(fields=['user', 'is_accessible'], name='automations_user_id_4fb677_idx')],
                'unique_together': {('user', 'page_id')},
            },
        ),
    ]
