version: '3.8'
services:
  backend:
    build: ./zapier-poc-backend
    ports:
      - "8080:8080"
    volumes:
      - ./zapier-poc-backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
  frontend:
    build: ./zapier-poc-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./zapier-poc-frontend:/app
    depends_on:
      - backend
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
volumes:
  mongo-data:
