services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - area-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - area-net

  server:
    build: ./backend
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${DB_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://redis:${REDIS_PORT}/0
    depends_on:
      - postgres
      - redis
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    networks:
      - area-net

  worker:
    build: ./backend
    env_file:
      - .env
    command: ["bash", "-c", "celery -A project worker --loglevel=info"]
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - area-net

  client_mobile:
    build: ./mobile
    volumes:
      - apk_shared:/shared
      - ./mobile:/app
    depends_on:
      - server
    networks:
      - area-net

  client_web:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - apk_shared:/shared
    depends_on:
      - client_mobile
      - server
    networks:
      - area-net

volumes:
  pgdata:
  pgadmin_data:
  redis-data:
  apk_shared:

networks:
  area-net:
