services:
  db:
    container_name: area_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - area-net

  pgadmin:
    container_name: area_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - area-net

  redis:
    container_name: area_redis
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - area-net

  server:
    container_name: area_server
    build: ./backend
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=area_project.settings
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - REDIS_URL=redis://redis:${REDIS_PORT}/0
    depends_on:
      - db
      - redis
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    networks:
      - area-net

  worker:
    container_name: area_worker
    build: ./backend
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: ["bash", "-c", "celery -A area_project worker --loglevel=info"]
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
    networks:
      - area-net

  client_mobile:
    container_name: area_client_mobile
    build: ./mobile
    volumes:
      - apk_shared:/shared
      - ./mobile:/app
    depends_on:
      - server
    networks:
      - area-net

  client_web:
    container_name: area_client_web
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - apk_shared:/shared
    depends_on:
      - client_mobile
      - server
    networks:
      - area-net

volumes:
  pgdata:
  pgadmin_data:
  redis-data:
  apk_shared:

networks:
  area-net:
