import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
              try {
                const k='area.theme';
                const t=localStorage.getItem(k);
                if(t==='light'||t==='dark'){
                  document.documentElement.setAttribute('data-theme', t);
                }
              } catch {}
            })();`,
          }}
        />
        <header className="px-4 py-3 border-b" style={{borderColor: 'var(--border)'}}>
          <div className="max-w-6xl mx-auto flex items-center justify-between">
            <nav className="flex gap-4">
              <a href="/">Home</a>
              <a href="/about">About</a>
              <a href="/users">Users</a>
              <a href="/services">Services</a>
              <a href="/areas">AREAs</a>
            </nav>
            <ThemeToggle />
          </div>
        </header>
        <div className="max-w-6xl mx-auto p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
