# Generated by Django 5.2.6 on 2025-10-13 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetoken",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Service Token",
                "verbose_name_plural": "Service Tokens",
            },
        ),
        migrations.AddField(
            model_name="servicetoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this token was used for an API call",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetoken",
            name="scopes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Space-separated list of granted OAuth2 scopes",
            ),
        ),
        migrations.AddField(
            model_name="servicetoken",
            name="token_type",
            field=models.CharField(
                default="Bearer", help_text="Token type (usually Bearer)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="servicetoken",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last token update (e.g., after refresh)"
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="access_token",
            field=models.TextField(help_text="Current OAuth2 access token"),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this token was first created"
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Token expiration time (None if never expires)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="refresh_token",
            field=models.TextField(
                blank=True,
                default="",
                help_text="OAuth2 refresh token (empty if not supported)",
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="service_name",
            field=models.CharField(
                db_index=True,
                help_text="OAuth2 provider name (e.g., google, github)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this OAuth2 token",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="servicetoken",
            index=models.Index(
                fields=["user", "service_name"], name="users_servi_user_id_616b44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetoken",
            index=models.Index(
                fields=["expires_at"], name="users_servi_expires_6279fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetoken",
            index=models.Index(
                fields=["service_name"], name="users_servi_service_d73cc6_idx"
            ),
        ),
    ]
